spring:
  application:
    name: transaction-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:secret@localhost:27017/transactiondb?authSource=admin}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: transaction-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.*"

server:
  port: 8082
  shutdown: graceful

spring.lifecycle:
  timeout-per-shutdown-phase: 20s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    com.example: DEBUG